name: JAVA CI SPRING BOOT

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - uses: actions/checkout@v4
      - name: SETUP JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: build with maven
        run: mvn clean install
        working-directory: .
      - name: show package
        run: "ls -la target"
      - name: show workspace
        run: "echo ${{ github.workspace }}"
      - name: Upload artifact for deployement
        uses: actions/upload-artifact@v2
        with:
          name: ynovbackend
          path: target/ynovbackend.jar

  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment: DEV
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v2
          with:
            name: ynovbackend
        - name: Azure Webapp
          uses: Azure/webapps-deploy@v3
          with:
            app-name: ynovbackend
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: '${{ github.workspace }}/target/*.jar'


