name: JAVA CI SPRING BOOT

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV

    env:
      AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }} # set this to the path to your web app project

    steps:
      - uses: actions/checkout@v4
      - name: SETUP JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: build with maven
        run: mvn -B package --file pom.xml
        working-directory: .
      - name: Azure Webapp
        uses: Azure/webapps-deploy@v3
        with:
          app-name: ynovbackend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.jar'


